
CREATE TABLE public.authors (
    id bigint NOT NULL,
    name character varying(255)
);

ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.bookcase_entry (
    id bigint NOT NULL,
    added_at date NOT NULL,
    reading_status character varying(255),
    review text,
    book_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT bookcase_entry_reading_status_check CHECK (((reading_status)::text = ANY ((ARRAY['WANT_TO_READ'::character varying, 'READING'::character varying, 'READ'::character varying])::text[])))
);

ALTER TABLE public.bookcase_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookcase_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.books (
    id bigint NOT NULL,
    cover_link character varying(255),
    description text,
    isbn bigint,
    pages_number integer,
    published_date date,
    title character varying(255),
    author_id bigint NOT NULL
);

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    birth date,
    gender character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255),
    role character varying(255),
    self_description character varying(255),
    CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.bookcase_entry
    ADD CONSTRAINT bookcase_entry_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT uk9mhkwvnfaarcalo4noabrin5j UNIQUE (name);

ALTER TABLE ONLY public.books
    ADD CONSTRAINT ukkibbepcitr0a3cpk3rfr7nihn UNIQUE (isbn);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.bookcase_entry
    ADD CONSTRAINT fk9v52ymcg39nkt67acppn2mhf3 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.books
    ADD CONSTRAINT fkfjixh2vym2cvfj3ufxj91jem7 FOREIGN KEY (author_id) REFERENCES public.authors(id);

ALTER TABLE ONLY public.bookcase_entry
    ADD CONSTRAINT fkq8jhxhurjsh51665yp9r1hhc6 FOREIGN KEY (book_id) REFERENCES public.books(id);